spring.application.name: rtl433-router
spring.profiles.active: ${PROFILE:local}

server.port: ${SERVER_PORT:4100}

info:
  app.name: ${spring.application.name}
  app.version: ${version:project.version}
  app.profile: ${spring.profiles.active}

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info

management.info:
  build.enabled: true
  env.enabled: true
  java.enabled: true
  os.enabled: true
